name: Build and Test

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'release/*'
  pull_request:
    branches:
      - develop
      - 'feature/*'
      - 'release/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers for faster builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build Docker images via docker-compose
      - name: Build Docker Images
        run: docker-compose build

      # Start containers and run tests
      - name: Run Integration Tests
        run: |
          docker-compose up -d
          # Wait for services to initialize; adjust sleep duration as needed
          sleep 10
          # Run tests inside the backend container (adjust command if needed)
          docker-compose exec backend pytest
          docker-compose down
