name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure AWS credentials (ensure these are set as GitHub secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          mask-aws-account-id: true

      # (Optional) Build Docker images if required for deployment
      - name: Build Docker Images
        run: docker-compose build

      # Deploy to the development instance (update the command as needed)
      - name: Deploy to AWS Fargate (Development)
        run: |
          echo "Deploying Thunder Buddy Development instance to AWS Fargate..."
          # Update the ECS service for development to force a new deployment
          aws ecs update-service --cluster thunder-buddy-dev-cluster --service thunder-buddy-dev-service --force-new-deployment
